/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Oscar
 */
public class ControlPanel extends javax.swing.JFrame {

    /**
     * Creates new form ControlPanel
     */
    public ControlPanel() {
        initComponents();
        init();
    }
    
    public void init(){
        jSliderControlSpeed = new javax.swing.JSlider(100,1200);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSetSnakeBodyColor = new javax.swing.JButton();
        jButtonSetSnakeHeadColor = new javax.swing.JButton();
        jButtonSetBgColor = new javax.swing.JButton();
        jButtonSetFoodColor = new javax.swing.JButton();
        jCheckBoxShowTableLine = new javax.swing.JCheckBox();
        jButtonReSet = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSliderControlSpeed = new javax.swing.JSlider();
        jSpinner = new javax.swing.JSpinner();
        jButtonSetGriddingColor = new javax.swing.JButton();
        jButtonSetGroundColor = new javax.swing.JButton();
        jButtonCloseFrame = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonSetSnakeBodyColor.setText("设置蛇身颜色");
        jButtonSetSnakeBodyColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSetSnakeBodyColorActionPerformed(evt);
            }
        });

        jButtonSetSnakeHeadColor.setText("设置蛇头颜色");
        jButtonSetSnakeHeadColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSetSnakeHeadColorActionPerformed(evt);
            }
        });

        jButtonSetBgColor.setText("设置背景颜色");
        jButtonSetBgColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSetBgColorActionPerformed(evt);
            }
        });

        jButtonSetFoodColor.setText("设置食物颜色");
        jButtonSetFoodColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSetFoodColorActionPerformed(evt);
            }
        });

        jCheckBoxShowTableLine.setText("显示网格线");

        jButtonReSet.setText("恢复默认设置");

        jLabel1.setText("贪吃蛇速度(ms)");

        jSliderControlSpeed.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderControlSpeedStateChanged(evt);
            }
        });
        jSliderControlSpeed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jSliderControlSpeedMousePressed(evt);
            }
        });

        jButtonSetGriddingColor.setText("设置网格颜色");

        jButtonSetGroundColor.setText("设置围墙颜色");

        jButtonCloseFrame.setText("确定");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCloseFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButtonReSet, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonSetSnakeBodyColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonSetBgColor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(jButtonSetGroundColor, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonSetFoodColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonSetSnakeHeadColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonSetGriddingColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCheckBoxShowTableLine, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSliderControlSpeed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonSetBgColor, jButtonSetFoodColor, jButtonSetSnakeHeadColor});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSetBgColor)
                    .addComponent(jButtonSetFoodColor))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSetSnakeBodyColor)
                    .addComponent(jButtonSetSnakeHeadColor))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSetGriddingColor)
                    .addComponent(jButtonSetGroundColor))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonReSet)
                    .addComponent(jCheckBoxShowTableLine))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSliderControlSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonCloseFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonReSet, jButtonSetGriddingColor, jButtonSetGroundColor, jButtonSetSnakeBodyColor});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jSliderControlSpeed, jSpinner});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSetBgColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSetBgColorActionPerformed
        callSetColor("设置背景颜色");
//        this.dispose();
    }//GEN-LAST:event_jButtonSetBgColorActionPerformed

    private void jButtonSetFoodColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSetFoodColorActionPerformed
        callSetColor("设置食物颜色");
    }//GEN-LAST:event_jButtonSetFoodColorActionPerformed

    private void jButtonSetSnakeBodyColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSetSnakeBodyColorActionPerformed
        callSetColor("设置贪吃蛇身体颜色");
    }//GEN-LAST:event_jButtonSetSnakeBodyColorActionPerformed

    private void jButtonSetSnakeHeadColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSetSnakeHeadColorActionPerformed
        callSetColor("设置贪吃蛇头部颜色");
    }//GEN-LAST:event_jButtonSetSnakeHeadColorActionPerformed

    private void jSliderControlSpeedStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderControlSpeedStateChanged
        jSpinner.setValue(jSliderControlSpeed.getValue());
    }//GEN-LAST:event_jSliderControlSpeedStateChanged

    private void jSliderControlSpeedMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderControlSpeedMousePressed
       jSpinner.setValue(jSliderControlSpeed.getValue());
    }//GEN-LAST:event_jSliderControlSpeedMousePressed

    private void callSetColor(String title){
        SetColorFrame setColorFrame = new SetColorFrame();
        setColorFrame.setTitle(title);
        setColorFrame.setResizable(false);
        setColorFrame.setVisible(true);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ControlPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCloseFrame;
    private javax.swing.JButton jButtonReSet;
    private javax.swing.JButton jButtonSetBgColor;
    private javax.swing.JButton jButtonSetFoodColor;
    private javax.swing.JButton jButtonSetGriddingColor;
    private javax.swing.JButton jButtonSetGroundColor;
    private javax.swing.JButton jButtonSetSnakeBodyColor;
    private javax.swing.JButton jButtonSetSnakeHeadColor;
    private javax.swing.JCheckBox jCheckBoxShowTableLine;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSlider jSliderControlSpeed;
    private javax.swing.JSpinner jSpinner;
    // End of variables declaration//GEN-END:variables
}
